### ISSUE TITLE
[translate.pl] Do I need to provide my own Google Translate API key?

### ISSUE THREAD

**Issue by eerie** [vovcacik/irssi-scripts#1]
19:39:16 -!- translate.pl: Google responded with error: 400 Bad Request
19:39:16 -!- Request details:
19:39:16 $VAR1 = {
19:39:16           'source' => 'en',
19:39:16           'target' => 'it',
19:39:16           'q' => 'hello guys',
19:39:16           'format' => 'text',
19:39:16           'key' => ''
19:39:16         };
19:39:16 
19:39:16 -!- Response content:
19:39:16 $VAR1 = '{
19:39:16  "error": {
19:39:16   "errors": [
19:39:16    {
19:39:16     "domain": "usageLimits",
19:39:16     "reason": "keyInvalid",
19:39:16     "message": "Bad Request"
19:39:16    }
19:39:16   ],
19:39:16   "code": 400,
19:39:16   "message": "Bad Request"
19:39:16  }
19:39:16 }
19:39:16 ';

So, a google API key is needed for real?

**Comment by vovcacik** [comment]
Yes, you need to make Google account and get your own key because Google Translate API is not free. Despite that I haven't payed a dime, but that would certainly change if I made the key public.
